'use client';
import { useState } from 'react';import { useSearchParams } from 'next/navigation';import Link from 'next/link';import { Filter,CalendarDays } from 'lucide-react';
import { usePortal } from './PortalProvider';import { ApplicationTable } from './ApplicationTable';import { Field } from './Field';import { clearanceTypes } from '@/data/clearanceTypes';import type { ApplicationStatus,UserRole } from '@/types';
const statuses:ApplicationStatus[]=['Draft','Pending Assessment','Awaiting OR','For Checking','Ready for Download','Closed - Cleared','Under Review','Void'];
export function ApplicationsList({role,processed=false,assessment=false}:{role:UserRole;processed?:boolean;assessment?:boolean}){
 const {state,user}=usePortal(),params=useSearchParams();const [q,setQ]=useState(params.get('q')||''),[status,setStatus]=useState<string>(assessment?'Pending Assessment':''),[type,setType]=useState(''),[filters,setFilters]=useState(false),[dates,setDates]=useState(false),[from,setFrom]=useState(''),[to,setTo]=useState('');
 const rows=state.applications.filter(a=>(role!=='resident'||a.residentId===user?.id)&&(role==='resident'||a.status!=='Draft')&&(!processed||['Ready for Download','Closed - Cleared'].includes(a.status))&&(!status||a.status===status)&&(!type||a.clearanceType===type)&&(!from||a.dateRequested.slice(0,10)>=from)&&(!to||a.dateRequested.slice(0,10)<=to)&&[a.reference,a.applicant,a.clearanceType].join(' ').toLowerCase().includes(q.toLowerCase()));
 const title=role==='resident'?'My Applications':role==='admin'?'Transactions':processed?'Processed Transactions':assessment?'Assessment & Evaluation':'Manage Applications';
 return <div className="p-5 md:p-8"><div className="flex justify-between gap-4 flex-wrap"><div><h1 className="text-[27px] font-bold text-brand-ink">{title}</h1><p className="text-[13px] mt-1 text-slate-600">{role==='resident'?'View and manage your clearance requests.':'Review and process clearance requests.'}</p></div><div className="flex gap-2 flex-wrap">{role==='staff'&&!processed&&<Link href="/staff/walk-in" className="primary-btn">+ New Walk-in Application</Link>}<button className="secondary-btn flex items-center gap-2" aria-expanded={filters} onClick={()=>setFilters(!filters)}><Filter size={14}/>Filter</button><button className="secondary-btn flex items-center gap-2" aria-expanded={dates} onClick={()=>setDates(!dates)}><CalendarDays size={14}/>Date Range</button></div></div><div className="mt-6"><Field label="Search applications"><input className="text-field max-w-md" placeholder="Search reference, name, or clearance type" value={q} onChange={e=>setQ(e.target.value)}/></Field></div>
 {role==='staff'&&!processed&&<div aria-label="Application status" className="flex gap-6 border-b mt-6 overflow-x-auto">{['','Pending Assessment','Awaiting OR','For Checking','Ready for Download','Closed - Cleared','Under Review'].map(s=><button type="button" key={s} aria-pressed={s===status} className={`pb-3 text-xs whitespace-nowrap ${s===status?'font-bold border-b-2 border-brand-primary text-brand-ink':''}`} onClick={()=>setStatus(s)}>{s||'All Applications'}</button>)}</div>}
 {filters&&<div className="form-grid mt-4"><Field label="Status"><select className="select-field" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{statuses.filter(s=>role==='resident'||s!=='Draft').map(s=><option key={s}>{s}</option>)}</select></Field><Field label="Clearance Type"><select className="select-field" value={type} onChange={e=>setType(e.target.value)}><option value="">All clearance types</option>{clearanceTypes.map(c=><option key={c.id}>{c.name}</option>)}</select></Field></div>}{dates&&<div className="form-grid mt-4"><Field label="From"><input type="date" className="text-field" value={from} max={to||undefined} onChange={e=>setFrom(e.target.value)}/></Field><Field label="To"><input type="date" className="text-field" value={to} min={from||undefined} onChange={e=>setTo(e.target.value)}/></Field></div>}<div className="mt-5"><ApplicationTable applications={rows} role={role}/></div></div>;
}
