'use client';
import Link from 'next/link'; import { useState } from 'react';
import type { Application, UserRole } from '@/types'; import { StatusBadge } from './StatusBadge'; import { dateLabel } from '@/lib/workflow';
export function applicationAction(a:Application,role:UserRole){
 if(role==='resident'){if(a.status==='Draft')return {label:'Continue Application',href:'/resident/apply?draft='+a.reference};if(a.status==='Awaiting OR')return {label:'View Assessment',href:'/resident/apply/pre-assessment?ref='+a.reference};if(a.status==='Ready for Download')return {label:'Download Clearance',href:'/resident/apply/ready?ref='+a.reference};}
 if(role==='staff'){if(a.status==='For Checking')return {label:'Verify Payment',href:'/staff/applications/'+a.reference};if(a.status==='Pending Assessment')return {label:'Review / Assess',href:'/staff/assessment/'+a.reference};if(a.status==='Awaiting OR')return {label:'Assist OR Entry',href:'/staff/or-entry?ref='+a.reference};}
 return {label:'View',href:'/'+role+'/applications/'+a.reference};
}
export function ApplicationTable({applications,role}:{applications:Application[];role:UserRole}){
 const [page,setPage]=useState(1);const pages=Math.max(1,Math.ceil(applications.length/6)),current=Math.min(page,pages);const rows=applications.slice((current-1)*6,current*6);
 return <div className="content-card"><div className="table-wrap"><table className="portal-table"><thead><tr><th>Reference No.</th>{role!=='resident'&&<th>Applicant</th>}<th>Clearance Type</th><th>Date Requested</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.map(a=>{const action=applicationAction(a,role);return <tr key={a.reference}><td className="whitespace-nowrap">{a.reference}</td>{role!=='resident'&&<td>{a.applicant}</td>}<td>{a.clearanceType}</td><td>{dateLabel(a.dateRequested)}</td><td><StatusBadge status={a.status}/></td><td><Link href={action.href} className="text-brand-primary font-semibold underline whitespace-nowrap">{action.label}</Link>{role==='resident'&&a.status==='Awaiting OR'&&<Link href={'/resident/apply/or?ref='+a.reference} className="block text-brand-primary underline mt-2">Enter OR</Link>}</td></tr>})}{!rows.length&&<tr><td colSpan={role==='resident'?5:6} className="text-center !py-8">No applications match your filters.</td></tr>}</tbody></table></div><div className="p-4 flex justify-between items-center text-xs gap-3"><span>{applications.length?((current-1)*6+1):0}–{Math.min(current*6,applications.length)} of {applications.length} requests</span><div className="flex items-center gap-3"><button className="secondary-btn !p-2" disabled={current===1} onClick={()=>setPage(current-1)} aria-label="Previous page">‹</button><span>Page {current} of {pages}</span><button className="secondary-btn !p-2" disabled={current===pages} onClick={()=>setPage(current+1)} aria-label="Next page">›</button></div></div></div>;
}
