'use client';
import { useState } from 'react'; import { useRouter, useSearchParams } from 'next/navigation';
import { CheckCircle2 } from 'lucide-react'; import Link from 'next/link';
import { clearanceTypes } from '@/data/clearanceTypes'; import { fullName } from '@/data/mockUsers';
import { usePortal } from './PortalProvider'; import { ProgressBar } from './ProgressBar'; import { FileUpload } from './FileUpload'; import { Field, ErrorMessage } from './Field'; import { StatusBadge } from './StatusBadge';
import { requirements, today } from '@/lib/workflow'; import type { ApplicationInput, UploadedDocument, User } from '@/types';
export function ApplicationForm({resident}:{resident?:User}) {
 const {user,state,act}=usePortal();const query=useSearchParams(),router=useRouter(); const person=resident||user!;
 const draft=state.applications.find(a=>a.reference===query.get('draft')&&a.residentId===person.id&&a.status==='Draft');
 const selected=clearanceTypes.find(c=>c.id===query.get('type'))?.name||'Business Clearance';
 const [form,setForm]=useState<ApplicationInput>(draft||{residentId:person.id,applicant:fullName(person),address:person.address,contact:person.contact,purpose:'',clearanceType:selected,businessName:'',businessLocation:'',initialOperation:'',applicationType:'New Application',ownership:'Owner',propertyOwner:'',businessContact:'',source:resident?'Assisted / Walk-in':'Online',documents:[],certified:false});
 const [reference,setReference]=useState(draft?.reference),[submitted,setSubmitted]=useState(''),[error,setError]=useState(''),[saved,setSaved]=useState(false);
 const isBusiness=form.clearanceType==='Business Clearance';
 function set<K extends keyof ApplicationInput>(key:K,value:ApplicationInput[K]){setForm(f=>({...f,[key]:value}));setSaved(false);}
 function save(asDraft:boolean){try{const next=act({type:'saveApplication',application:{...form,documents:form.documents.filter(d=>requirements(form).some(r=>r.name===d.requirement))},reference,draft:asDraft});const record=next.applications.find(a=>a.reference===reference)||next.applications[0];setReference(record.reference);setError('');if(asDraft)setSaved(true);else setSubmitted(record.reference);}catch(e){setError((e as Error).message);}}
 if(submitted)return <div className="px-6 py-12 max-w-[760px] mx-auto"><div className="content-card p-10 text-center"><CheckCircle2 size={48} className="text-green-600 mx-auto"/><h1 className="text-2xl font-bold text-brand-ink mt-4">Application Submitted</h1><p className="text-sm mt-3 text-slate-600">Your request has been received and is now pending assessment.</p><div className="mt-5 bg-slate-50 border py-4"><p className="text-xs text-slate-500">Request Reference No.</p><p className="text-xl font-bold text-brand-ink my-2">{submitted}</p><StatusBadge status="Pending Assessment"/></div><p className="text-sm text-slate-600 mt-4">The Pre-Assessment Slip will be available after Staff completes the assessment.</p><Link href={resident?'/staff/applications':'/resident/applications'} className="primary-btn inline-block mt-6">{resident?'Applications Queue':'My Applications'}</Link></div></div>;
 return <div className="pb-12"><div className="sticky top-0 z-30 border-b border-slate-300 bg-white px-6 md:px-10 py-5"><div className="max-w-[720px] mx-auto"><h1 className="text-[27px] font-bold text-brand-ink">Clearance Application</h1>{resident&&<p className="text-xs mt-2">Assisted / Walk-in • {fullName(person)}</p>}<div className="mt-3"><ProgressBar step={1} title="Application Details"/></div></div></div><form onSubmit={e=>{e.preventDefault();save(false);}} className="max-w-[590px] mx-4 sm:mx-auto mt-9 content-card px-6 sm:px-9 py-8">
 <h2 className="text-[21px] font-bold text-brand-ink border-b pb-2">Section 1 - Owner / Applicant Information</h2><div className="space-y-5 mt-5"><Field label="Full Name *"><input required className="text-field" value={form.applicant} onChange={e=>set('applicant',e.target.value)}/></Field><Field label="Complete Address *"><textarea required className="textarea-field min-h-[65px]" value={form.address} onChange={e=>set('address',e.target.value)}/></Field><Field label="Contact Number *"><input type="tel" required className="text-field" placeholder="09123456789" value={form.contact} onChange={e=>set('contact',e.target.value)}/></Field><Field label="Purpose of Clearance *"><input required className="text-field" placeholder="State the purpose of the clearance" value={form.purpose} onChange={e=>set('purpose',e.target.value)}/></Field></div>
 <h2 className="text-[21px] font-bold text-brand-ink border-y py-3 mt-8">Section 2 - Business / Property Information</h2><div className="mt-5"><Field label="Clearance Type *"><select className="select-field" value={form.clearanceType} onChange={e=>set('clearanceType',e.target.value)}>{clearanceTypes.map(c=><option key={c.id}>{c.name}</option>)}</select></Field></div>
 <div className="mt-5 border border-slate-300 bg-surface-muted p-5"><p className="text-xs font-semibold text-brand-primary mb-5">{form.clearanceType} Details</p><div className="space-y-4">
 {isBusiness&&<Field label="Name of Business *"><input required className="text-field" value={form.businessName} onChange={e=>set('businessName',e.target.value)}/></Field>}
 <Field label={isBusiness?'Location of Business *':'Property / Activity Address *'}><input required className="text-field" value={form.businessLocation} onChange={e=>set('businessLocation',e.target.value)}/></Field>
 {isBusiness&&<><Field label="Date of Initial Operation *"><input type="date" max={today()} required className="text-field" value={form.initialOperation} onChange={e=>set('initialOperation',e.target.value)}/></Field><fieldset><legend className="field-label">Application Type</legend><div className="flex flex-wrap gap-5 text-xs">{(['New Application','Renewal'] as const).map(value=><label key={value}><input type="radio" name="application-type" checked={form.applicationType===value} onChange={()=>set('applicationType',value)} className="mr-2"/>{value}</label>)}</div></fieldset><Field label="Contact Number *"><input type="tel" required className="text-field" value={form.businessContact} onChange={e=>set('businessContact',e.target.value)}/></Field></>}
 <fieldset><legend className="field-label">Ownership</legend><div className="flex gap-5 text-xs flex-wrap">{(['Owner','Renter','Occupant'] as const).map(value=><label key={value}><input type="radio" name="ownership" checked={form.ownership===value} onChange={()=>set('ownership',value)} className="mr-2"/>{value}</label>)}</div></fieldset>{form.ownership!=='Owner'&&<Field label="Name of Property Owner *"><input required className="text-field" value={form.propertyOwner} onChange={e=>set('propertyOwner',e.target.value)}/></Field>}</div></div>
 <h2 className="text-[21px] font-bold text-brand-ink border-y py-3 mt-8">Section 3 - Document Upload</h2><p className="text-xs text-slate-600 mt-4">Please upload clear, legible copies. JPG, PNG, PDF. Max 5 MB each.</p><div className="grid sm:grid-cols-2 gap-4 mt-5">{requirements(form).map(r=><FileUpload key={r.name} label={r.name} required={r.required} value={form.documents.find(d=>d.requirement===r.name)} idCard={r.name.includes('ID')} onChange={file=>set('documents',[...form.documents.filter(d=>d.requirement!==r.name),...(file?[file]:[])])}/>)}</div>
 <label className="mt-8 border border-brand-border bg-brand-soft px-4 py-4 flex gap-4 text-xs leading-4 font-semibold"><input required type="checkbox" checked={form.certified} onChange={e=>set('certified',e.target.checked)}/>I hereby certify that the above information is true and correct to the best of my knowledge and belief.</label><ErrorMessage message={error}/>{saved&&<p role="status" className="text-sm text-green-700 mt-3">Draft saved: {reference}</p>}<div className="flex gap-2 flex-wrap justify-end mt-8 pt-5 border-t"><button type="button" className="secondary-btn" onClick={()=>save(true)}>Save Draft</button><button className="primary-btn">Submit Application</button></div></form></div>;
}
