'use client';
import Link from 'next/link';import { PaymentVerification } from './PaymentVerification';import { ReplaceDocuments } from './ReplaceDocuments';import { CorrectionRequests } from './CorrectionRequests';import { usePortal } from './PortalProvider';import { StatusBadge } from './StatusBadge';import { FeeTable } from './FeeTable';import { ReportTable } from './ReportTable';import { applicationAction } from './ApplicationTable';import { dateLabel } from '@/lib/workflow';import { processingSeconds,SLA_SECONDS } from '@/data/mockReports';import { DocumentPreview } from './DocumentPreview';import { useState } from 'react';import type { UploadedDocument } from '@/types';
export function ApplicationDetail({reference}:{reference:string}) {
 const {state,user}=usePortal();const [doc,setDoc]=useState<UploadedDocument>();const a=state.applications.find(a=>a.reference===reference&&(user?.role!=='resident'||a.residentId===user.id));
 if(!a)return <div className="p-8"><h1 className="text-xl font-bold">Application Not Found</h1><p className="mt-3">This request is unavailable for your account.</p></div>;
 const action=applicationAction(a,user!.role),duration=processingSeconds(a);
 return <div className="p-5 md:p-8 max-w-[1100px] mx-auto"><div className="flex justify-between gap-4 flex-wrap items-start"><div><h1 className="text-[27px] font-bold text-brand-ink">Application Details</h1><p className="text-sm mt-2">{a.reference}</p></div><StatusBadge status={a.status}/></div>
 {a.rejection&&<div className="content-card p-5 mt-6 border-l-4 border-l-red-600 bg-red-50"><p className="text-xs font-bold text-red-800 uppercase tracking-wide">Application Rejected</p><p className="text-sm mt-2 text-red-900">{a.rejection.reason}</p><p className="text-xs text-slate-500 mt-2">Rejected by {a.rejection.rejectedBy} • {dateLabel(a.rejection.timestamp)}</p></div>}
 <CorrectionRequests application={a}/>
 <div className="content-card p-6 mt-6"><dl className="form-grid">{Object.entries({'Applicant':a.applicant,'Clearance Type':a.clearanceType,...(a.clearanceType==='Business Clearance'?{'Business Subcategory':a.businessSubcategory||'Business Clearance only'}:{}),'Complete Address':a.address,'Contact Number':a.contact,'Purpose of Clearance':a.purpose,'Application Type':a.applicationType,'Business / Property Location':a.businessLocation,'Business Name':a.clearanceType==='Business Clearance'?a.businessName:'—','Ownership':a.ownership,'Property Owner':a.propertyOwner||'—','Employees':a.hasEmployees===undefined?'—':a.hasEmployees?(a.employeeCount!=null?`Yes (${a.employeeCount})`:'Yes'):'No','Date Requested':dateLabel(a.dateRequested),'Source':a.source}).map(([key,value])=><div key={key}><dt className="text-xs text-slate-500">{key}</dt><dd className="text-sm font-semibold mt-1">{value}</dd></div>)}</dl></div>
 <ReplaceDocuments application={a}/>
 <h2 className="text-lg font-bold text-brand-ink mt-7 mb-3">Documents</h2><ReportTable headers={['Document','File','Status','Action']} rows={a.documents.map(d=>[d.requirement,d.name,<>{d.status}{d.note&&<span className="block text-xs text-slate-500">{d.note}</span>}</>,<button key={d.requirement} className="text-brand-primary underline" onClick={()=>setDoc(d)}>View</button>])}/>
 {a.assessment&&<div className="content-card p-6 mt-6"><h2 className="text-lg font-bold text-brand-ink mb-4">Assessment</h2><p className="text-sm mb-4">{a.assessment.category} {a.assessment.classification} • Assessed by {a.assessment.assessedBy}</p><FeeTable items={a.assessment.items}/></div>}
 <PaymentVerification key={a.paymentVerification?.submittedAt} application={a}/>
 {a.receipt&&<div className="content-card p-6 mt-6"><h2 className="font-bold mb-3">Official Receipt Details</h2><p className="text-sm">{a.receipt.orNumber} • {a.receipt.orDate} • ₱{a.receipt.amountPaid.toFixed(2)}</p><p className="text-xs text-slate-500 mt-1">Encoded by: {a.receipt.encodedBy}</p>{a.receipt.receiptPhoto&&<button className="text-sm text-brand-primary underline mt-3 block" onClick={()=>setDoc(a.receipt!.receiptPhoto)}>View Uploaded Receipt Photo</button>}</div>}
 {a.simulatedPayment&&<div className="content-card p-6 mt-6 border-l-4 border-l-amber-400"><div className="flex items-center gap-2 mb-2"><span className="text-xs font-bold bg-amber-100 text-amber-800 border border-amber-300 px-2 py-0.5 rounded">SIMULATION</span><h2 className="font-bold">Online Payment (Simulated)</h2></div><dl className="form-grid mt-3">{Object.entries({'Payment Method':a.simulatedPayment.method,'Simulation Reference':a.simulatedPayment.referenceNumber,'Amount':'₱'+a.simulatedPayment.amount.toFixed(2),'Paid At':dateLabel(a.simulatedPayment.paidAt)}).map(([k,v])=><div key={k}><dt className="text-xs text-slate-500">{k}</dt><dd className="text-sm font-semibold mt-1">{v}</dd></div>)}</dl><p className="text-xs text-amber-700 mt-4 border border-amber-200 bg-amber-50 px-3 py-2 rounded">{a.simulatedPayment.note}</p></div>}
 {user?.role!=='resident'&&<div className="mt-6"><h2 className="text-lg font-bold mb-3 text-brand-ink">Service Processing</h2><ReportTable headers={['Milestone','Recorded Value']} rows={[['Request Time',dateLabel(a.dateRequested)],['Assessment Time',dateLabel(a.assessment?.assessedAt)],['OR Entry Time',dateLabel(a.receipt?.recordedAt)],['Clearance Generated Time',dateLabel(a.clearance?.generatedAt)],['Completion Time',dateLabel(a.confirmation?.completionTime)],['Processing Duration',duration===null?'—':String(Math.floor(duration/60)).padStart(2,'0')+':'+String(Math.round(duration%60)).padStart(2,'0')],['SLA Status',duration===null?'Not started':duration<=SLA_SECONDS?'Within SLA':'Outside SLA']]}/><p className="text-xs text-slate-500 mt-2">Sample SLA: {SLA_SECONDS} seconds from OR entry to clearance generation.</p>{a.inspection&&<p className="text-sm mt-4">Inspection: {a.inspection.status} • {a.inspection.inspector} • {a.inspection.date} • {a.inspection.remarks}</p>}</div>}
 {a.confirmation&&<p className="text-sm mt-5">Receipt confirmed: {dateLabel(a.confirmation.timestamp)}. IP: {a.confirmation.ipPlaceholder}.</p>}
 <div className="flex gap-3 mt-6 flex-wrap"><Link href={'/'+user?.role+'/'+(user?.role==='admin'?'transactions':'applications')} className="secondary-btn">Back to applications</Link>{action.href!=='/'+user?.role+'/applications/'+a.reference&&<Link href={action.href} className="primary-btn">{action.label}</Link>}{user?.role==='resident'&&a.status==='Closed - Cleared'&&<Link href={'/resident/apply/ready?ref='+a.reference} className="primary-btn">View Clearance</Link>}</div>{doc&&<DocumentPreview document={doc} onClose={()=>setDoc(undefined)}/>}</div>;
}
