'use client';
import Link from 'next/link';import { ClipboardCheck,ReceiptText,Archive,CircleCheck,ClipboardList,Gauge,Star,Clock3 } from 'lucide-react';
import { usePortal } from './PortalProvider';import { StatCard } from './StatCard';import { ApplicationTable } from './ApplicationTable';import { ReportTable } from './ReportTable';import { dateLabel } from '@/lib/workflow';import { processingSeconds,SLA_SECONDS } from '@/data/mockReports';import type { UserRole } from '@/types';
export function Dashboard({role}:{role:UserRole}){
 const {state,user}=usePortal();const apps=state.applications.filter(a=>(role!=='resident'||a.residentId===user?.id)&&a.status!=='Draft');
 const times=apps.map(processingSeconds).filter((n):n is number=>n!==null),ratings=apps.flatMap(a=>a.feedback?[a.feedback.rating]:[]);
 const metrics=[{label:'Pending Assessment',value:apps.filter(a=>a.status==='Pending Assessment').length,icon:ClipboardCheck},{label:'Awaiting OR',value:apps.filter(a=>a.status==='Awaiting OR').length,icon:ReceiptText},{label:'Ready for Download',value:apps.filter(a=>a.status==='Ready for Download').length,icon:Archive},{label:'Closed - Cleared',value:apps.filter(a=>a.status==='Closed - Cleared').length,icon:CircleCheck}];
 if(role==='admin'){metrics.unshift({label:'Total Applications',value:apps.length,icon:ClipboardList});}
 return <div className="px-5 md:px-8 py-12 max-w-[1250px] mx-auto"><h1 className="text-[27px] font-bold text-brand-ink">{role==='resident'?`Welcome back, ${user?.firstName}!`:role==='admin'?'Admin Dashboard':'Staff Dashboard'}</h1><p className="text-sm mt-2 text-slate-700">{role==='resident'?'Track and manage your clearance applications here.':'Service requests and processing overview.'}</p><div className="grid sm:grid-cols-2 md:grid-cols-4 gap-4 mt-9">{metrics.map(m=><StatCard key={m.label} {...m}/>)}{role==='admin'&&<><StatCard label="Requests Within SLA" value={times.length?Math.round(times.filter(t=>t<=SLA_SECONDS).length/times.length*100)+'%':'—'} icon={Gauge}/><StatCard label="Average Processing Time" value={times.length?(times.reduce((a,b)=>a+b,0)/times.length).toFixed(1)+'s':'—'} icon={Clock3}/><StatCard label="Average Satisfaction Rating" value={ratings.length?(ratings.reduce((a,b)=>a+b,0)/ratings.length).toFixed(1)+'/5':'—'} icon={Star}/></>}</div>{role==='admin'?<><p className="text-xs text-slate-500 mt-3">Processing duration measures OR entry to clearance generation. Sample SLA target: {SLA_SECONDS} seconds.</p><h2 className="text-xl font-bold text-brand-ink mt-10 mb-5">Recent Activity</h2><ReportTable headers={['Time','User','Action','Reference']} rows={state.audits.slice(0,8).map(a=>[dateLabel(a.timestamp),a.user,a.action,a.reference])}/></>:<><h2 className="text-xl font-bold text-brand-ink mt-10 mb-5">Recent Applications</h2><ApplicationTable applications={apps.slice(0,5)} role={role}/><div className="text-right mt-5"><Link href={'/'+role+'/applications'} className="text-sm text-brand-primary underline">View all applications →</Link></div></>}</div>;
}

