'use client';
import { Upload, IdCard } from 'lucide-react';
import { useId, useRef, useState } from 'react';
import type { UploadedDocument } from '@/types';
import { validFile } from '@/lib/workflow';
export function FileUpload({label,helper,required,persist=false,idCard=false,value,onChange}:{label:string;helper?:string;required?:boolean;persist?:boolean;idCard?:boolean;value?:UploadedDocument;onChange?:(file:UploadedDocument|undefined)=>void}) {
  const [selected,setSelected]=useState<UploadedDocument>(); const [error,setError]=useState(''); const input=useRef<HTMLInputElement>(null); const id=useId(); const file=value||selected; const Icon=idCard?IdCard:Upload;
  async function choose(f?:File) { if(!f)return; if(!validFile(f)){setError('Choose a JPG, PNG, or PDF file no larger than 5 MB.'); if(input.current)input.current.value=''; return;} const next:UploadedDocument={requirement:label,name:f.name,size:f.size,type:f.type,status:'Pending Review',url:persist?await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(f);}):URL.createObjectURL(f)}; if(file?.url)URL.revokeObjectURL(file.url); setSelected(next); onChange?.(next);setError(''); }
  return <div><label htmlFor={id} className="field-label">{label}{required&&<span className="text-red-600"> *</span>}</label><div className="border border-dashed border-brand-border min-h-[115px] flex flex-col items-center justify-center text-center p-4 bg-white" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();choose(e.dataTransfer.files[0]);}}><Icon size={24} className="text-brand-muted mb-2"/><label htmlFor={id} className="cursor-pointer text-xs font-semibold break-all">{file?.name||'Click to upload or drag and drop'}</label><input id={id} ref={input} type="file" accept=".jpg,.jpeg,.png,.pdf" className="sr-only" aria-describedby={id+'-help'} aria-invalid={!!error} onChange={e=>choose(e.target.files?.[0])}/><span id={id+'-help'} className="text-xs text-slate-500 mt-2">{helper||'JPG, PNG, PDF • Max 5 MB'}</span>{file&&<button type="button" className="text-xs underline mt-2" onClick={()=>{if(file.url)URL.revokeObjectURL(file.url);setSelected(undefined);onChange?.(undefined);if(input.current)input.current.value='';}}>Remove file</button>}</div>{error&&<p role="alert" className="text-xs text-red-700 mt-2">{error}</p>}</div>;
}
