'use client';
import { BarangayLogo } from './BarangayLogo';
import { useState } from 'react';import Link from 'next/link';import { useRouter,useSearchParams } from 'next/navigation';import { Info,AlertTriangle,LockKeyhole,CheckCircle2,Download } from 'lucide-react';
import { usePortal } from './PortalProvider';import { ProgressBar } from './ProgressBar';import { FeeTable } from './FeeTable';import { Field,ErrorMessage,Notice } from './Field';import { FeedbackModal } from './FeedbackModal';import { formatPeso } from '@/data/revenueCodeData';import { today,dateLabel } from '@/lib/workflow';import { applicationPDF } from '@/lib/downloads';import { ClearanceQR } from './ClearanceQR';
export function WorkflowPage({step,staff=false}:{step:2|3|4;staff?:boolean}) {
 const {state,user,act}=usePortal(),params=useSearchParams(),router=useRouter();const reference=params.get('ref');
 const allowed=state.applications.filter(a=>(staff||a.residentId===user?.id)&&(step===4?['Ready for Download','Closed - Cleared'].includes(a.status):a.status==='Awaiting OR'));
 const a=allowed.find(x=>x.reference===reference);const [error,setError]=useState(''),[feedback,setFeedback]=useState(false),[message,setMessage]=useState('');
 const route=staff?'/staff/or-entry':'/resident/apply/'+(step===2?'pre-assessment':step===3?'or':'ready');
 if(!a||!a.assessment||(step===4&&(!a.receipt||!a.clearance)))return <div className="max-w-[760px] mx-auto p-6 md:py-10"><h1 className="text-[27px] font-bold text-brand-ink">{staff?'Assist OR Entry':'Clearance Application'}</h1><div className="content-card p-6 mt-6"><h2 className="font-bold">{reference?'This step is unavailable for this request.':'Select an application'}</h2><p className="text-sm mt-3 text-slate-600">{step===2?'Staff assessment must be complete before viewing the Pre-Assessment Slip.':step===3?'OR details can be entered only after Staff completes assessment.':'A clearance is available only after OR details have been recorded.'}</p><div className="space-y-3 mt-5">{allowed.map(x=><Link key={x.reference} href={route+'?ref='+x.reference} className="block border p-3 text-sm text-brand-primary hover:bg-brand-soft">{x.reference} • {x.clearanceType} • {x.applicant}</Link>)}</div>{!allowed.length&&<p className="text-sm mt-5">No requests are currently at this step.</p>}<Link href={staff?'/staff/applications':'/resident/applications'} className="secondary-btn inline-block mt-5">Back to applications</Link></div></div>;
 const finish=()=>{setFeedback(false);router.push('/resident/applications');};
 return <div className="px-5 md:px-8 py-8 max-w-[850px] mx-auto"><h1 className="text-[27px] font-bold text-brand-ink mb-5">{staff?'Assist OR Entry':'Clearance Application'}</h1><div className={step===2?'content-card p-5':''}><ProgressBar step={step} title={step===2?'Fee Breakdown & Pre-Assessment':step===3?'Enter Official Receipt Details':'Clearance Ready for Download'}/></div><ErrorMessage message={error}/>{message&&<Notice>{message}</Notice>}
 {step===2&&<div className="content-card mt-7 overflow-hidden"><div className="bg-brand-soft border-b border-brand-border p-5 flex gap-4 text-xs"><Info size={18} className="shrink-0"/>Present your Pre-Assessment Slip at the Municipal Treasury. After payment, return to the portal and enter the Official Receipt details issued by the Treasury.</div><div className="p-6 sm:p-8"><dl className="form-grid text-sm mb-6">{Object.entries({'Reference No.':a.reference,'Clearance Type':a.clearanceType,'Application Type':a.applicationType,...(a.clearanceType==='Business Clearance'?{'Business Category':a.assessment.category,'Classification / Scale':a.assessment.classification}:{})}).map(([k,v])=><div key={k}><dt className="text-xs text-slate-500">{k}</dt><dd className="font-semibold mt-1">{v}</dd></div>)}</dl><FeeTable items={a.assessment.items}/><p className="text-xs text-slate-500 mt-6">Illustrative fees from the configured sample assessment schedule.</p><button className="secondary-btn mt-6 flex items-center gap-2" onClick={()=>{applicationPDF(a,'assessment');setMessage('Pre-Assessment Slip download started.');}}><Download size={16}/>Download Pre-Assessment Slip (PDF)</button></div><div className="bg-surface-muted border-t px-8 py-5 flex justify-between"><Link href="/resident/applications" className="secondary-btn">Back</Link><Link href={'/resident/apply/or?ref='+a.reference} className="primary-btn">Next</Link></div></div>}
 {step===3&&<div className="content-card mt-8 overflow-hidden"><div className="bg-red-50 border-b border-red-100 p-5 flex gap-4"><AlertTriangle size={19} className="text-red-600 shrink-0"/><div><p className="text-sm font-semibold">Action Required</p><p className="text-xs mt-1 text-slate-600">Your clearance PDF cannot be generated until Official Receipt details are submitted.</p></div></div><form className="px-6 sm:px-10 py-9 text-center" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{act({type:'or',reference:a.reference,number:String(f.get('number')).trim(),date:String(f.get('date')),amount:String(f.get('amount'))});router.push(staff?'/staff/applications/'+a.reference:'/resident/apply/ready?ref='+a.reference);}catch(e){setError((e as Error).message);}}}><div className="w-12 h-12 rounded-lg bg-slate-100 text-brand-primary grid place-items-center mx-auto"><LockKeyhole size={25}/></div><h2 className="text-[21px] font-bold mt-3">Enter Official Receipt Details</h2><p className="text-xs text-slate-600 mt-2">Record the details issued by the Municipal Treasury.</p><p className="text-sm font-semibold mt-4">{a.reference} • {a.clearanceType}</p><div className="text-left max-w-[390px] mx-auto mt-8"><Field label="Official Receipt (OR) Number *"><input name="number" className="text-field" placeholder="TR-2026-12345" required pattern="TR-[0-9]{4}-[0-9]{5}"/></Field><div className="form-grid mt-5"><Field label="OR Date *"><input name="date" type="date" max={today()} className="text-field" required/></Field><Field label="Amount Paid *"><input name="amount" inputMode="decimal" className="text-field" required placeholder={a.assessment.total.toFixed(2)}/></Field></div><p className="text-xs text-slate-500 mt-3">Assessed Amount: <strong>{formatPeso(a.assessment.total)}</strong></p><p className="text-xs text-slate-500 mt-3">These details are recorded locally. There is no live Treasury database verification.</p><div className="mt-6 flex justify-between gap-2"><Link href={staff?'/staff/applications':'/resident/apply/pre-assessment?ref='+a.reference} className="secondary-btn">Back</Link><button className="primary-btn">Submit OR Details</button></div></div></form></div>}
 {step===4&&<div className="text-center pt-9"><div className="mx-auto w-[70px] h-[70px] rounded-lg bg-brand-soft grid place-items-center"><CheckCircle2 size={34} className="text-brand-primary"/></div><h2 className="text-[27px] font-bold mt-5">Clearance Ready for Download</h2><p className="text-sm text-slate-600 mt-3">Your clearance document is now available.</p><div className="mx-auto mt-8 w-full max-w-[340px] content-card border-t-[3px] border-t-brand-primary p-4"><div className="bg-surface-muted p-5 text-left"><BarangayLogo size={40} className="mx-auto"/><p className="text-center font-bold text-sm mt-3">{a.clearanceType}</p><p className="text-xs text-center text-slate-500 mt-1">SAMPLE — NOT AN OFFICIAL DOCUMENT</p><dl className="text-xs space-y-3 mt-5">{Object.entries({'Reference No.':a.reference,'OR Number':a.receipt!.orNumber,'Issue Date':a.clearance!.issueDate}).map(([k,v])=><div key={k}><dt className="text-slate-500">{k}</dt><dd className="font-semibold">{v}</dd></div>)}</dl>{a.clearance!.revisedFrom&&<p className="text-xs text-amber-800 mt-3">REVISED - Original on {a.clearance!.revisedFrom}</p>}<div className="flex justify-end mt-4"><ClearanceQR reference={a.reference}/></div></div></div><div className="mt-5 grid gap-2 max-w-[280px] mx-auto"><button className="primary-btn flex items-center justify-center gap-2" onClick={()=>{try{applicationPDF(a,'clearance');act({type:'download',reference:a.reference});setMessage('Clearance PDF download started.');}catch(e){setError((e as Error).message);}}}><Download size={16}/>Download Clearance PDF</button><button className="secondary-btn" disabled={!a.clearance!.downloadedAt||!!a.confirmation} onClick={()=>{try{act({type:'confirm',reference:a.reference});setFeedback(true);}catch(e){setError((e as Error).message);}}}>{a.confirmation?'Receipt Confirmed':'Confirm Receipt'}</button></div><p className="text-xs text-slate-500 mt-4">Download your clearance before confirming receipt.</p>{a.confirmation&&<p className="text-sm text-green-700 mt-4">Closed - Cleared • {dateLabel(a.confirmation.timestamp)}</p>}</div>}
 {feedback&&<FeedbackModal onClose={finish} onSubmit={(rating,comment)=>{act({type:'feedback',reference:a.reference,rating,comment});finish();}}/>}</div>;
}
