'use client';
import { useState } from 'react';import { usePortal } from '@/components/PortalProvider';import { Field,ErrorMessage,Notice } from '@/components/Field';import { PasswordInput } from '@/components/PasswordInput';import { Modal } from '@/components/Modal';import { ConfirmationModal } from '@/components/ConfirmationModal';import { ReportTable } from '@/components/ReportTable';import { fullName } from '@/data/mockUsers';import { dateLabel } from '@/lib/workflow';import type { User } from '@/types';
export default function UsersPage(){
 const {state,act}=usePortal();const [tab,setTab]=useState<'resident'|'staff'>('resident'),[q,setQ]=useState(''),[editing,setEditing]=useState<User>(),[reset,setReset]=useState<User>(),[toggle,setToggle]=useState<User>(),[error,setError]=useState(''),[message,setMessage]=useState('');
 const users=state.users.filter(u=>u.role===tab&&[fullName(u),u.email].join(' ').toLowerCase().includes(q.toLowerCase()));
 function save(u:User,reason:string){act({type:'user',user:u,reason});setMessage(reason+'.');setError('');}
 return <div className="p-5 md:p-8"><div className="flex justify-between gap-4 flex-wrap"><div><h1 className="text-[27px] font-bold text-brand-ink">User Management</h1><p className="text-[13px] mt-1 text-slate-600">Manage Resident and Staff user accounts.</p></div><button className="primary-btn" onClick={()=>{setError('');setEditing({id:crypto.randomUUID(),firstName:'',lastName:'',email:'',password:'',role:tab,status:'Active',contact:'',address:'',createdAt:new Date().toISOString()});}}>+ Create User</button></div><div className="flex gap-6 border-b mt-7" role="tablist" aria-label="Account role">{(['resident','staff'] as const).map(t=><button role="tab" aria-selected={tab===t} key={t} onClick={()=>setTab(t)} className={`pb-3 text-sm ${tab===t?'font-bold text-brand-ink border-b-2 border-brand-primary':'text-slate-600'}`}>{t==='resident'?'Residents':'Staff'}</button>)}</div><div className="mt-5 max-w-md"><Field label="Search name, email, or username"><input value={q} onChange={e=>setQ(e.target.value)} className="text-field" placeholder="Search name, email, or username"/></Field></div>{message&&<Notice>{message}</Notice>}<div className="mt-5"><ReportTable headers={['Name','Email / Username','Role','Status','Created At','Action']} rows={users.map(u=>[fullName(u),u.email,u.role==='resident'?'Resident':'Staff',u.status,dateLabel(u.createdAt),<div key="actions" className="flex flex-wrap gap-3 text-brand-primary"><button className="underline" onClick={()=>{setError('');setEditing({...u});}}>Edit</button><button className="underline" onClick={()=>{setError('');setReset(u);}}>Reset Password</button><button className="underline" onClick={()=>setToggle(u)}>{u.status==='Active'?'Deactivate':'Activate'}</button></div>])}/></div>
 {editing&&<Modal title={state.users.some(u=>u.id===editing.id)?'Edit User':'Create User'} onClose={()=>setEditing(undefined)}><form className="mt-5 space-y-4" onSubmit={e=>{e.preventDefault();try{save(editing,state.users.some(u=>u.id===editing.id)?'User updated':'User created');setEditing(undefined);}catch(e){setError((e as Error).message);}}}><div className="form-grid"><Field label="First Name *"><input className="text-field" required value={editing.firstName} onChange={e=>setEditing({...editing,firstName:e.target.value})}/></Field><Field label="Last Name *"><input className="text-field" required value={editing.lastName} onChange={e=>setEditing({...editing,lastName:e.target.value})}/></Field></div><Field label="Email / Username *"><input className="text-field" required value={editing.email} onChange={e=>setEditing({...editing,email:e.target.value})}/></Field><div className="form-grid"><Field label="Role"><select className="select-field" value={editing.role} onChange={e=>setEditing({...editing,role:e.target.value as 'resident'|'staff'})}><option value="resident">Resident</option><option value="staff">Staff</option></select></Field><Field label="Contact Number"><input type="tel" className="text-field" value={editing.contact} onChange={e=>setEditing({...editing,contact:e.target.value})}/></Field></div>{!state.users.some(u=>u.id===editing.id)&&<Field label="Temporary Password *"><PasswordInput minLength={8} required value={editing.password} autoComplete="new-password" onChange={e=>setEditing({...editing,password:e.target.value})}/></Field>}<ErrorMessage message={error}/><div className="flex justify-end gap-2"><button type="button" className="secondary-btn" onClick={()=>setEditing(undefined)}>Cancel</button><button className="primary-btn">Save User</button></div></form></Modal>}
 {reset&&<Modal title="Reset Password" onClose={()=>setReset(undefined)}><p className="text-sm mt-4">Set a temporary password for {fullName(reset)}.</p><form className="mt-4" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{save({...reset,password:String(f.get('password'))},'Password reset');setReset(undefined);}catch(e){setError((e as Error).message);}}}><Field label="Temporary Password *"><PasswordInput name="password" required minLength={8} autoComplete="new-password"/></Field><ErrorMessage message={error}/><button className="primary-btn mt-5">Reset Password</button></form></Modal>}
 {toggle&&<ConfirmationModal title={toggle.status==='Active'?'Deactivate Account':'Activate Account'} onClose={()=>setToggle(undefined)} onConfirm={()=>{save({...toggle,status:toggle.status==='Active'?'Inactive':'Active'},toggle.status==='Active'?'Account deactivated':'Account activated');setToggle(undefined);}}>{toggle.status==='Active'?'Deactivate':'Activate'} {fullName(toggle)}&apos;s prototype account?</ConfirmationModal>}</div>;
}
