'use client';
import Link from 'next/link';
import { useRouter, useSearchParams } from 'next/navigation';
import { useState } from 'react';
import { usePortal } from '@/components/PortalProvider';
import { Field, ErrorMessage } from '@/components/Field';
import { PasswordInput } from '@/components/PasswordInput';
export default function LoginPage(){
 const router=useRouter(),query=useSearchParams();const {act}=usePortal();const [staff,setStaff]=useState(false),[error,setError]=useState('');
 return <div className="min-h-screen bg-page-bg flex items-start justify-center pt-[60px] px-4"><form className="content-card w-full max-w-[325px] px-9 py-9" onSubmit={e=>{e.preventDefault();try{const f=new FormData(e.currentTarget);const s=act({type:'login',email:String(f.get('email')),password:String(f.get('password')),staffLogin:staff});const user=s.users.find(u=>u.id===s.currentUserId)!;const next=query.get('next');router.push(next?.startsWith('/'+user.role+'/')?next:'/'+user.role+'/dashboard');}catch(e){setError((e as Error).message);}}}><div className="text-center"><h1 className="text-[25px] font-bold text-brand-ink">{staff?'Staff / Admin Login':'Login'}</h1><p className="text-xs text-slate-600 mt-3">Access your Barangay San Jose account.</p></div><div className="mt-8 space-y-4"><Field label="Email or Username"><input name="email" autoComplete="username" required className="text-field" placeholder="Enter your email or username"/></Field><Field label="Password"><PasswordInput name="password" autoComplete="current-password" required placeholder="Enter your password"/></Field></div><ErrorMessage message={error}/><button className="primary-btn w-full mt-6">Login</button><Link href="/" className="secondary-btn w-full mt-3 block text-center">Back to Home</Link><p className="text-xs text-center mt-8">Don&apos;t have an account? <Link href="/register" className="underline text-brand-primary">Register</Link></p><button type="button" className="text-xs underline text-brand-primary block mx-auto mt-5" onClick={()=>{setStaff(!staff);setError('');}}>{staff?'Resident Login':'Staff/Admin Login'}</button><p className="text-xs text-center mt-4 text-slate-500"><Link href="/information#privacy" className="underline">Privacy Notice</Link></p></form></div>;
}
